[package]
name = "reth-bittorrent"
version = "0.1.0"
edition = "2021"
authors = ["mandreyel <mandreyel@protonmail.com>", "mattsse <matthias.seitz@outlook.de>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/foundry-rs/reth"
keywords = ["bittorrent", "torrent", "p2p", "networking"]
readme = "README.md"
description = """
Reth bittorrent downloader
"""

[dependencies]

# torrent
bitvec = "1.0"
serde_bencode = "0.2"
percent-encoding = "2.1"

# async/futures
futures = "0.3"
reqwest = "0.11"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "net", "time", "io-util", "fs"] }
tokio-util = { version = "0.7", features = ["codec"] }
tokio-stream = "0.1"
pin-project = "1.0"

# misc
bytes = "1.2"
byteorder = "1.4"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
sha1 = "0.10"
thiserror = "1.0"
url = "2.3"
fnv = "1.0"
tracing = "0.1"
typed-builder = "0.10"
lru = "0.8.1"
hex = "0.4.3"

[target.'cfg(target_os = "linux")'.dependencies]
nix = "0.25"

[dev-dependencies]
tempfile = "3.3"
